### ISSUE TITLE
Remove PDFs from Repo

### ISSUE THREAD

**Issue by jashmenn** [qq83387856/angular2#2]
Hi! I'm the co-author of ng-book 1 and ng-book 2. Making these books is our full time job and the only way we're able to keep them up-to-date is if people buy the book.

I'm stoked you think our work is worth sharing, but we'd like for you to remove the PDFs from the repo. Glad you like the book though!

**Comment by qq83387856** [comment]
I am sorry,I will do it

**Comment by qq83387856** [comment]
the pdf has been removed from ths Reop.
